# Generated by Django 3.2.12 on 2022-03-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_time',)},
        ),
    ]
